### ISSUE TITLE
BuildError werkzeug.routing.exceptions.BuildError

### ISSUE THREAD

**Issue by imlauera** [pj8912/merge-for-shorts#6]
I get this error message when I try to crop to shorts
BuildError
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'merge' with values ['success', 'video']. Did you mean 'altmerge' instead?

**Comment by pj8912** [comment]
Fixed it!

**Comment by pj8912** [comment]
give it a star if you like the project!

**Comment by imlauera** [comment]
Thanks
